# Generated by Django 2.0.3 on 2018-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.AddField(
            model_name='item',
            name='img_big',
            field=models.ImageField(blank=True, upload_to='', verbose_name='изображение (большое)'),
        ),
        migrations.AddField(
            model_name='item',
            name='img_small',
            field=models.ImageField(blank=True, upload_to='', verbose_name='изображение (маленькое)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='имя'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['vendor_code'], name='mainapp_ite_vendor__3414a3_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['vendor_code'], name='mainapp_pri_vendor__694322_idx'),
        ),
        migrations.AddIndex(
            model_name='quantity',
            index=models.Index(fields=['vendor_code'], name='mainapp_qua_vendor__bbe196_idx'),
        ),
    ]
