# Generated by Django 2.0.3 on 2018-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180325_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.DecimalField(blank=0, decimal_places=0, max_digits=8, verbose_name='количество'),
        ),
    ]
