# Generated by Django 2.0.3 on 2018-03-31 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0005_auto_20180331_2251'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=0, decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.DecimalField(blank=0, decimal_places=0, max_digits=8, verbose_name='количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ItemCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='PastPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=0, decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.DecimalField(blank=0, decimal_places=0, max_digits=8, verbose_name='количество')),
                ('buydate', models.DateTimeField(verbose_name='дата/время покупки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ItemCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-buydate', 'user'],
            },
        ),
    ]
