# Generated by Django 2.0.3 on 2018-04-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastpurchases',
            options={'ordering': ['-add_datetime', 'user']},
        ),
        migrations.RenameField(
            model_name='pastpurchases',
            old_name='buydate',
            new_name='add_datetime',
        ),
    ]
