# Generated by Django 2.0.3 on 2018-04-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0004_auto_20180401_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=models.PositiveIntegerField(blank=0, default=0, primary_key=True, serialize=False, verbose_name='номер ордера покупки'),
        ),
    ]
