# Generated by Django 2.0.3 on 2018-04-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0005_auto_20180401_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='номер ордера покупки'),
        ),
    ]
