# Generated by Django 2.0.3 on 2018-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0007_auto_20180401_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpurchases',
            name='add_datetime',
            field=models.DateTimeField(null=True, verbose_name='дата/время покупки'),
        ),
    ]
