# Generated by Django 2.0.3 on 2018-04-01 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0008_auto_20180401_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpurchases',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата/время покупки'),
            preserve_default=False,
        ),
    ]
